#!/bin/bash
## Description: Run PHPUnit inside the ddev web container
## Usage: phpunit [phpunit-args]
## Example: "ddev phpunit --testdox"

PLUGIN_DIR="${SEILER_DDEV_DIR:-/var/www/html/wp-content/themes/seiler-2026-theme}"
PHPUNIT_BIN="${SEILER_PHPUNIT_BIN:-vendor-dev/bin/phpunit}"

cd "$PLUGIN_DIR" || exit 1
exec "$PHPUNIT_BIN" "$@"
